title: Kyle Boutell
logo: docs/assets/images/Headshot.jpg
description: >
  <h4>M.S. Applied Data Science for Business</h4>
  <em>Portland State University, June 2025</em>
  <br></br>
  I graduated last month and I am now looking for a full time Business Analytics role that will allow me to continue to grow my skills.
#show_downloads: True
theme: jekyll-theme-minamal
