title: Kyle Boutell
logo: docs/assets/images/Headshot.jpg
description: >
  <strong>M.S. Applied Data Science for Business</strong>
  <em>Portland State University, June 2025</em>
  <br></br>
  I recently earned my Master’s in Applied Data Science for Business from Portland State University and am now seeking a full time Business Analyst role where I can continue to grow my analytical skills. With a background that combines technical training and real world experience I’ve developed a strong foundation in data analysis, visualization and statistical modeling. My work has included projects in machine learning, forecasting and process improvement. I enjoy finding practical insights that help teams solve problems and make informed decisions. I’m especially drawn to roles that bridge technical tools and human workflows, and I’m excited to keep learning while adding value through my work.
#show_downloads: True
theme: jekyll-theme-minimal
