title: Kyle Boutell
logo: kboutell/docs/assets/images/Headshot.jpg
description: I recently graduated with my Master's in Applied Data Science for Business from Portland State University. Now I am looking for a role that will allow me to put my skills into practice.
#show_downloads: True
theme: jekyll-theme-slate
