title: Kyle Boutell
logo: docs/assets/images/Headshot.jpg
description: >
  <strong>M.S. Applied Data Science for Business</strong>
  <em>Portland State University, June 2025</em>
  <br></br>
  I recently earned my Master’s in Applied Data Science for Business from Portland State University and am now seeking a full time Business Analyst role where I can continue to grow my skills.
  <a href="www.linkedin.com/in/kyle-boutell">LinkedIn Profile</a>
#show_downloads: True
theme: jekyll-theme-minimal
